version: 2
updates:
  # GitHub Actions dependency updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"

  # Python dependencies - pfSense MCP
  - package-ecosystem: "pip"
    directory: "/pfsense-mcp"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "python"
      - "pfsense-mcp"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    groups:
      # Group patch updates together to reduce PR noise
      patch-updates:
        patterns:
          - "*"
        update-types:
          - "patch"
      # Group minor updates together
      minor-updates:
        patterns:
          - "*"
        update-types:
          - "minor"

  # Python dependencies - TrueNAS MCP
  - package-ecosystem: "pip"
    directory: "/truenas-mcp"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "python"
      - "truenas-mcp"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    groups:
      patch-updates:
        patterns:
          - "*"
        update-types:
          - "patch"
      minor-updates:
        patterns:
          - "*"
        update-types:
          - "minor"

  # Python dependencies - iDRAC MCP
  - package-ecosystem: "pip"
    directory: "/idrac-mcp"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "python"
      - "idrac-mcp"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    groups:
      patch-updates:
        patterns:
          - "*"
        update-types:
          - "patch"
      minor-updates:
        patterns:
          - "*"
        update-types:
          - "minor"

  # Python dependencies - Proxmox MCP
  - package-ecosystem: "pip"
    directory: "/proxmox-mcp"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "python"
      - "proxmox-mcp"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    groups:
      patch-updates:
        patterns:
          - "*"
        update-types:
          - "patch"
      minor-updates:
        patterns:
          - "*"
        update-types:
          - "minor"
