blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/filthyrake/damens_mcps/discussions
    about: Ask questions, share ideas, or discuss with the community
  - name: 🔒 Security Advisory
    url: https://github.com/filthyrake/damens_mcps/security/advisories/new
    about: Report security vulnerabilities privately (PREFERRED for security issues)
  - name: 📖 Documentation
    url: https://github.com/filthyrake/damens_mcps/blob/main/README.md
    about: Read the documentation and project guides
