name: Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible to help us understand your request.

  - type: dropdown
    id: project
    attributes:
      label: Which project should this feature be added to?
      description: Select the MCP server project for this feature
      options:
        - pfSense MCP
        - TrueNAS MCP
        - iDRAC MCP
        - Proxmox MCP
        - Repository/Infrastructure
        - Multiple projects
        - New project
    validations:
      required: true

  - type: dropdown
    id: type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - New MCP tool/capability
        - Improvement to existing tool
        - New deployment option (Docker, K8s, etc.)
        - Documentation enhancement
        - Developer experience improvement
        - Performance optimization
        - Security enhancement
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Is your feature request related to a problem?
      placeholder: |
        Example: I'm frustrated when I need to [do something] because [reason]...
        Or: Currently there's no way to [do something]...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: |
        Example: Add a new MCP tool called 'tool_name' that allows...
        Or: Modify the existing 'tool_name' to also support...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: |
        Example: I considered using [alternative approach] but it doesn't work because...

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe how you would use this feature
      placeholder: |
        Example workflow:
        1. User calls tool with parameters...
        2. Tool performs action...
        3. User receives result...
    validations:
      required: true

  - type: textarea
    id: benefits
    attributes:
      label: Benefits
      description: What are the benefits of implementing this feature?
      placeholder: |
        - Benefit 1
        - Benefit 2
        - Who would benefit from this?

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical (blocking my use case)
        - High (would significantly improve my workflow)
        - Medium (would be nice to have)
        - Low (minor convenience)
    validations:
      required: true

  - type: textarea
    id: technical
    attributes:
      label: Technical Considerations
      description: Any technical details, API references, or implementation notes
      placeholder: |
        - Platform API documentation: [link]
        - Similar features in other tools: [examples]
        - Potential challenges: [notes]

  - type: textarea
    id: examples
    attributes:
      label: Examples / References
      description: Any examples of similar features in other projects, mockups, or references
      placeholder: |
        - Similar tool in project X: [link]
        - Documentation showing the capability: [link]

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to contribute to this feature?
      options:
        - label: I am willing to implement this feature myself
          required: false
        - label: I can help test this feature
          required: false
        - label: I can help with documentation
          required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please verify the following before submitting
      options:
        - label: I have searched for similar feature requests and this is not a duplicate
          required: true
        - label: I have checked the project documentation to ensure this doesn't already exist
          required: true
        - label: This feature aligns with the project's goals
          required: false
