name: Security Vulnerability
description: Report a security vulnerability (use private reporting instead!)
title: "[SECURITY] "
labels: ["security"]
body:
  - type: markdown
    attributes:
      value: |
        ## ⚠️ STOP! Please Read This First
        
        **For security vulnerabilities, please use GitHub's private vulnerability reporting instead of creating a public issue:**
        
        1. Go to the [Security tab](https://github.com/filthyrake/damens_mcps/security)
        2. Click "Report a vulnerability"
        3. Fill out the private report form
        
        **Why private reporting?**
        - Prevents attackers from exploiting the vulnerability before it's fixed
        - Allows coordinated disclosure with security community
        - Protects users currently running the software
        
        **Only use this public template if:**
        - The vulnerability is already publicly known
        - It's been previously reported and fixed
        - You're discussing general security improvements (not a specific vulnerability)
        
        ---
        
        If you're certain you want to continue with a public report, please proceed below.

  - type: dropdown
    id: project
    attributes:
      label: Which project is affected?
      description: Select the MCP server project with the vulnerability
      options:
        - pfSense MCP
        - TrueNAS MCP
        - iDRAC MCP
        - Proxmox MCP
        - Repository/Infrastructure
        - Multiple projects
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity (if known)
      description: Estimated severity of the vulnerability
      options:
        - Critical (Remote code execution, data breach)
        - High (Authentication bypass, privilege escalation)
        - Medium (Information disclosure, DoS)
        - Low (Minor security improvement)
        - Unknown
    validations:
      required: true

  - type: dropdown
    id: type
    attributes:
      label: Vulnerability Type
      description: What type of vulnerability is this?
      options:
        - Command Injection
        - Path Traversal
        - SQL Injection
        - Authentication Bypass
        - Privilege Escalation
        - Information Disclosure
        - Credential Exposure
        - Denial of Service
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Vulnerability Description
      description: High-level description of the vulnerability (no exploit details!)
      placeholder: Describe the vulnerability without providing exploitation details...
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Potential Impact
      description: What could an attacker do if they exploited this vulnerability?
      placeholder: |
        Example: An attacker could...
        - Impact 1
        - Impact 2
    validations:
      required: true

  - type: textarea
    id: affected
    attributes:
      label: Affected Versions
      description: Which versions are affected?
      placeholder: |
        - All versions
        - Versions 1.0.0 to 1.5.0
        - Specific commit range

  - type: textarea
    id: mitigation
    attributes:
      label: Suggested Mitigation
      description: Do you have suggestions for how to fix this?
      placeholder: |
        Example:
        - Add input validation for parameter X
        - Use parameterized queries instead of string concatenation
        - Implement proper authentication checks

  - type: textarea
    id: references
    attributes:
      label: References
      description: Links to relevant security advisories, CVEs, or documentation
      placeholder: |
        - CVE-YYYY-XXXXX
        - OWASP reference: [link]
        - Similar vulnerability: [link]

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the vulnerability
      placeholder: Add any other context here...

  - type: checkboxes
    id: confirmation
    attributes:
      label: Confirmation
      description: Please confirm the following
      options:
        - label: I understand this is a public issue and will not include exploit code or detailed attack instructions
          required: true
        - label: I have considered using private vulnerability reporting instead
          required: true
        - label: This vulnerability is already publicly known OR I'm discussing general security improvements
          required: true
