name: Test MCP Servers

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test-pfsense:
    name: Test pfSense MCP
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        cd pfsense-mcp
        pip install -r requirements.txt
        pip install pytest pytest-cov pytest-asyncio pytest-mock
    
    - name: Run tests
      run: |
        cd pfsense-mcp
        pytest tests/ -v --cov=src --cov-report=xml --cov-report=term
    
    - name: Upload coverage
      uses: codecov/codecov-action@v5
      with:
        file: ./pfsense-mcp/coverage.xml
        flags: pfsense
        name: pfsense-coverage

  test-truenas:
    name: Test TrueNAS MCP
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        cd truenas-mcp
        pip install -r requirements.txt
        pip install pytest pytest-cov pytest-asyncio pytest-mock
    
    - name: Run tests
      run: |
        cd truenas-mcp
        pytest tests/ -v --cov=src --cov-report=xml --cov-report=term
    
    - name: Upload coverage
      uses: codecov/codecov-action@v5
      with:
        file: ./truenas-mcp/coverage.xml
        flags: truenas
        name: truenas-coverage

  test-idrac:
    name: Test iDRAC MCP
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        cd idrac-mcp
        pip install -r requirements.txt
        pip install pytest pytest-cov pytest-asyncio pytest-mock
    
    - name: Run tests
      run: |
        cd idrac-mcp
        pytest tests/ -v --cov=src --cov-report=xml --cov-report=term
    
    - name: Upload coverage
      uses: codecov/codecov-action@v5
      with:
        file: ./idrac-mcp/coverage.xml
        flags: idrac
        name: idrac-coverage

  test-proxmox:
    name: Test Proxmox MCP
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        cd proxmox-mcp
        pip install -r requirements.txt
        pip install pytest pytest-cov pytest-asyncio pytest-mock
    
    - name: Run tests
      run: |
        cd proxmox-mcp
        pytest tests/test_unit.py tests/test_validation_security.py -v --cov=src --cov-report=xml --cov-report=term
    
    - name: Upload coverage
      uses: codecov/codecov-action@v5
      with:
        file: ./proxmox-mcp/coverage.xml
        flags: proxmox
        name: proxmox-coverage
